<a href="https://colab.research.google.com/github/tomafischer/ai_geeks/blob/main/Python_Snippets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import numpy as np
import pandas as pd

# General: Directory, Path functions, Formating

Conda create python environment
```
conda create --name python=3.9
```
### Jupyter 
Autocomplete
```
%config Completer.use_jedi = False
setting indentation to 2 
```
https://stackoverflow.com/questions/19068730/how-do-i-change-the-autoindent-to-2-space-in-ipython-notebook
```javascript
var cell = Jupyter.notebook.get_selected_cell();
var config = cell.config;
var patch = {
      CodeCell:{
        cm_config:{indentUnit:2}
      }
    }
config.update(patch)
```


In [12]:
#shows all variables
%whos

Variable       Type      Data/Info
----------------------------------
current_path   str       /
np             module    <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
os             module    <module 'os' from '/usr/lib/python3.7/os.py'>
sample_mean    float     3.2344
st             module    <module 'scipy.stats' fro<...>scipy/stats/__init__.py'>
sys            module    <module 'sys' (built-in)>


In [9]:
# clear the workspace
%reset -sf

In [11]:
#### Python version
import sys
import os
import numpy as np
print(f"python version: {sys.version}")

#####
#   Directory, Path functions
#####
# Get current directory
current_path = os.getcwd()
print(os.getcwd())
#get file name from path
os.path.basename(current_path)
os.chdir('../')



#string formating 
sample_mean = 3.2344
print(f'We have determined the mean of the population to be {sample_mean:.2f}')



import scipy.stats as st
st.norm.rvs(loc= 3, scale=2, size=6)

python version: 3.7.12 (default, Sep 10 2021, 00:21:48) 
[GCC 7.5.0]
/
We have determined the mean of the population to be 3.23


array([ 3.0314927 ,  2.61193682, -0.37117757,  3.035198  ,  4.3989898 ,
        2.89420159])

# List operations: from List to string

In [6]:
###
# to string from list
###
list1 = [1, 2, 3,4 ]
list2 = [str(i) for i in list1]
','.join(list2)
str1 = ','.join(str(e) for e in list1 if e%2)
print(str1)

1,3


# Conditional for if

In [7]:
l = [1,2,3,4]
",".join([str(i) for i in l if i%2==0])

'2,4'

# Random, shuffeling

In [ ]:
####
#.   Random
####
## integers
np.random.randint(1,100)
#44
data = np.random.randint(1,100,10)
#array([13, 64, 27, 63, 46, 68, 92, 10, 58, 24])

#random float unform
np.random.rand(1)[0]

#uniform distribution over [0, 1)
np.random.rand(2)
#array([ 0.11570539,  0.35279769])

#Return a sample (or samples) from the "standard normal" distribution
np.random.randn(2)
# -> array([-0.27954018,  0.90078368])

rows = 20 # rows (m)
cols = 6 # columns (n)
rand_np = np.random.randn(rows, cols)

#shuffling data
np.random.shuffle(data)

In [ ]:
# inline if
# expression_if_true if condition else expression_if_false
a= 2
1 if a>0 else 0

print(f"a > 0? : {1 if a>0 else 0}")
#wine_data_normalized['boolQuality']=wine_data_normalized['quality'].apply(lambda x: 1 if x> 5 else 0)

# inline list calculation
ts = [ t+t for t in range(5)]
print(ts)

a > 0? : 1


# Datetime

In [ ]:
########
#   Datetime
########
from datetime import datetime, timedelta
start_dt = datetime(2021,10,6) # Wednesday
#time add or subtract
add_dt = start_dt + timedelta(days=6)
end_dt = datetime.strptime('2020-01-01 18:27:25', "%Y-%m-%d %H:%M:%S")
#Print weekday
print(start_dt.strftime("%a"))


def date_parse_iso_seconds_fraction(date_str, format_str='%Y-%m-%d %H:%M:%S', verbose= False):
  #if no date, return None
  if date_str is None:
    return None
  try:
    last_dot = date_str.rfind('.') 
    digits = len(date_str) - last_dot - 1
    
    date_ts = datetime.strptime(date_str[0:last_dot], format_str)#.timestamp()
    fraction_str = date_str[last_dot+1:len(date_str)]
    fraction = float(fraction_str) / 10**digits
    date_ts += timedelta(seconds=fraction)
    if verbose:
      print(f'digits: {digits} : {fraction_str}')
    return date_ts
      
  except Exception as ex:
    raise ex
    if verbose:
      print(ex)
    return None

class Test_Date(unittest.TestCase):
  def test_date_parse_iso_seconds_fraction(self):
    # arrange
    dates =['2020-01-01 18:27:25.1','2020-01-01 18:27:25.12','2020-01-01 18:27:25.123',
            '2020-01-01 18:27:25.1234','2020-01-01 18:27:25.12345','2020-01-01 18:27:25.123456']
    
    # act
    results = [date_parse_iso_seconds_fraction(str) for str in dates]
    #print(results)
    # assert
    self.assertEqual(results[0].microsecond,1 * 1e5)
    self.assertEqual(results[1].microsecond,12 * 1e4)
    self.assertEqual(results[2].microsecond,123 * 1e3)
    self.assertEqual(results[3].microsecond,1234 * 1e2)
    self.assertEqual(results[4].microsecond,12345 * 1e1)
    self.assertEqual(results[5].microsecond,123456 )
unittest.main(argv=[''], verbosity=2, exit=False) 

test_date_parse_iso_seconds_fraction (__main__.Test_Date) ... ok
test_add_int (__main__.Test_add_int) ... 

Wed


ok

----------------------------------------------------------------------
Ran 2 tests in 0.006s

OK


In [ ]:
datetime.now().timestamp()

1635282194.981052

#Enumerations and Iterations

In [ ]:
####
#. Enumerations and Iterations
###
for i,v in enumerate([11,22,33]):
  print(f"Enumerate enum:{i} value: {v}")

for i in range(2,3):
  print(f"Range value {i}")

#will get you the next element 
n = next(iter([11,22,33]))
print(f"Next/First {n}")

iteration = iter([11,22,33])
for i in range(3):
  print(next(iteration))

Enumerate enum:0 value: 11
Enumerate enum:1 value: 22
Enumerate enum:2 value: 33
Range value 2
Next/First 11
11
22
33


# Numpy and Pandas
```
np.hstack - np.vastck to combine arrays

```

In [27]:
import numpy as np
# Create data 
#np array of discreat values
'''The essential difference between NumPy linspace and NumPy arange is that 
linspace enables you to control the precise end value, whereas arange gives you 
more direct control over the increments between values in the sequence.
'''
start_interval =1
end_inerval = 20
howmany =10
interval =0.5
np.linspace(start_interval, end_inerval, howmany)  
np.arange(start_interval, end_inerval, interval)

rows = 20 # rows (m)
cols = 6 # columns (n)
data_np  = np.zeros((rows,cols))
rand_np = np.random.randn(rows, cols)

In [19]:
import pandas as pd
import numpy as np
a_np = np.array([[11,22,33],[44,55,66]])
# numpy to pandas
a_pd = pd.DataFrame(a_np, columns=['a','b','c'])

## pandas to json/dict
a_json = a_pd.to_json(orient='records')
a_pd.to_dict('records')
## json to pandas
a2_pd = pd.read_json(a_json) # could also be a file path or url
print(a2_pd)

    a   b   c
0  11  22  33
1  44  55  66


In [ ]:

a_np = np.array([[11,22,33],[44,55,66]])
# numpy to pandas
a_pd = pd.DataFrame(a_np, columns=['a','b','c'])

##### 
#    Combining two Numpy/Array into Pandas Array
#####
N = 100
data1 = np.random.rand(N)
data2 = np.random.randn(N)
# use vstack to combine data and then transpose
data_np = np.vstack((data1, data2)).T
data_pd = pd.DataFrame(data = data_np, columns = ["Random", "Normal"])
print(data_pd)
# or using a dictonary for creation
data2_pd = pd.DataFrame(data = {"Random": data1, "Normal" :data2})


### Combine both with hstack to combine features already in the right shape 
b_np = a_np.copy() + 40
ab_np = np.hstack((a_pd, b_np))
ab_pd = pd.DataFrame(ab_np, columns=['a','b','c','d','e','f'])
print(ab_pd)

# use vsatck to add to numby one dimensonal arrays to a data series
N = 100
data1 = np.random.rand(N)
data2 = np.random.randn(N)
# use vstack to combine data and then transpose
data_np = np.vstack((data1, data2)).T
data_pd = pd.DataFrame(data = data_np, columns = ["Random", "Normal"])

### from and to JSON
ab2_dict ={ 'A':1,'B':2 }
#from dict
ab2_pd = pd.DataFrame([ab2_dict])
#to json
ab2_json = ab2_pd.to_json(orient='records')
print(f"json: {ab2_json}")
ab3_dict = ab2_pd.to_dict('records')
print(f"dict: {ab3_dict}")

      Random    Normal
0   0.470923 -0.205153
1   0.110652 -0.386213
2   0.476152  1.478430
3   0.294141 -0.550930
4   0.077866  0.058423
..       ...       ...
95  0.359723  0.030086
96  0.954855 -0.294603
97  0.535340  0.216102
98  0.283317 -0.510530
99  0.702384 -0.413734

[100 rows x 2 columns]
      Random    Normal
0   0.470923 -0.205153
1   0.110652 -0.386213
2   0.476152  1.478430
3   0.294141 -0.550930
4   0.077866  0.058423
..       ...       ...
95  0.359723  0.030086
96  0.954855 -0.294603
97  0.535340  0.216102
98  0.283317 -0.510530
99  0.702384 -0.413734

[100 rows x 2 columns]
    a   b   c   d   e    f
0  11  22  33  51  62   73
1  44  55  66  84  95  106
json: [{"A":1,"B":2}]
dict: [{'A': 1, 'B': 2}]


In [ ]:
#############
#     Unit testing
#############
import unittest
# function to be tested
def add_int(a:int,b:int ) -> int:
  return a+b

# Test class
class Test_add_int(unittest.TestCase):
  def test_add_int(self):
    # arrange
    a = 2
    b =3
    # act
    c = add_int(a, b)
    # assert
    self.assertEqual(c, a+b, ' test for sum')

# running the tests
unittest.main(argv=[''], verbosity=2, exit=False)    

test_add_int (__main__.Test_add_int) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.004s

OK


# Arg parsing

In [21]:
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--pmu_name', type=str, help='PMU name',required=True)
parser.add_argument('--learning_rate', type=float, help="Model name",required=True)
parser.add_argument('--batch_size', type=int, help="Size of batch",required=True)

args = parser.parse_args()

pmu_name = args.pmu_name

usage: ipykernel_launcher.py [-h] --pmu_name PMU_NAME --learning_rate
                             LEARNING_RATE --batch_size BATCH_SIZE
ipykernel_launcher.py: error: the following arguments are required: --pmu_name, --learning_rate, --batch_size


SystemExit: ignored

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2890: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
